apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demoapp
        image: bobfleming/k8s-demo-app:1.0
        ports:
        - containerPort: 80
        env:
        - name: "APP_NAME"
          value: "demo-app"
        - name: "APP_VERSION"
          value: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: demo-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
