apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: foo
  name: first-app
  labels:
    app: first-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: firstapp
          image: bobfleming/k8s-demo-app:1.0
          ports:
            - containerPort: 80
          env:
            - name: "APP_NAME"
              value: "first-app"
            - name: "APP_VERSION"
              value: "1.0"
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: first-app
spec:
  selector:
    app: first-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
